# Generated by Django 2.1.5 on 2019-03-18 00:18

from django.db import migrations, models

PERIODS = [
    {
        "period_sequence": 10,
        "period_name": "Spring"
    },
    {
        "period_sequence": 20,
        "period_name": "Summer"
    },
    {
        "period_sequence": 30,
        "period_name": "Fall"
    },
    {
        "period_sequence": 9999,
        "period_name": "TemporaryValue"
    }
]


# migration forward procedure
def add_calendar_period_data(apps, schema_editor):
    target_model = apps.get_model("courseinfo", "Period")
    for v in PERIODS:
        orm_obj = target_model.objects.create(
            period_sequence=v["period_sequence"],
            period_name=v["period_name"]
        )


# migration backward procedure
def remove_calendar_period_data(apps, schema_editor):
    target_model = apps.get_model("courseinfo", "Period")
    for v in PERIODS:
        orm_obj = target_model.objects.get(
            period_sequence=v["period_sequence"],
        )
        orm_obj.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('courseinfo', '0003_auto_20190317_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_sequence', models.IntegerField(unique=True)),
                ('period_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['period_sequence'],
            },
        ),
        migrations.RunPython(
            add_calendar_period_data,
            remove_calendar_period_data
        )
    ]
