# Generated by Django 2.1.5 on 2019-03-18 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courseinfo', '0006_semester_schema_and_data_conversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year__year', 'period__period_sequence']},
        ),
        migrations.AlterField(
            model_name='semester',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters',
                                    to='courseinfo.Period'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters',
                                    to='courseinfo.Year'),
        ),
    ]
